name: ci

on: [push, pull_request]

jobs:
  examples:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: False
      matrix:
        python-version:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libpython2.7  # required by paup
          python -m pip install --upgrade pip
      - name: Install paup
        run: |
          temp_dir=$(mktemp -d)
          wget -P ${temp_dir} http://phylosolutions.com/paup-test/paup4a168_ubuntu64.gz
          gunzip ${temp_dir}/paup4a168_ubuntu64.gz
          chmod +x ${temp_dir}/paup4a168_ubuntu64
          sudo mv ${temp_dir}/paup4a168_ubuntu64 /usr/local/bin/paup
          echo "export DENDROPY_PAUP_EXECUTABLE_PATH=/usr/local/bin/paup" >> "${GITHUB_ENV}"
      - name: Install dendropy
        run: |
          python -m pip install .
      - name: Run examples
        run: |
          cd docs/source/examples
          # only allow known failures
          # and enforce removal of working examples from known failures
          for f in *.py; do
            echo "${f}"
            if timeout 10 python3 "${f}" && ! grep -q "${f}" backlogged-fail-whitelist.txt; then
              :
            elif grep -q "${f}" backlogged-fail-whitelist.txt; then
              :
            else
              exit 1
            fi
          done
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff check --format=github --select=E9,F63,F7,F82 --extend-exclude=docs/source/schemas/interfaces --target-version=py37 .
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: False
      matrix:
        python-version:
          - "2.7"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libpython2.7  # required by paup
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install paup
        run: |
          temp_dir=$(mktemp -d)
          wget -P ${temp_dir} http://phylosolutions.com/paup-test/paup4a168_ubuntu64.gz
          gunzip ${temp_dir}/paup4a168_ubuntu64.gz
          chmod +x ${temp_dir}/paup4a168_ubuntu64
          sudo mv ${temp_dir}/paup4a168_ubuntu64 /usr/local/bin/paup
          echo "export DENDROPY_PAUP_EXECUTABLE_PATH=/usr/local/bin/paup" >> "${GITHUB_ENV}"
      - name: Install dendropy
        run: |
          python -m pip install .
      - name: Test with setup.py
        run: |
          python setup.py test
